"""Add fresh semantic tool-call wording families after failed held-out scores."""

from collections import Counter
import hashlib
import json
from pathlib import Path
import random
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from wrench.pilot_tasks import public_record  # noqa: E402
from wrench.protocol import canonical_json  # noqa: E402
from wrench.release_data import make_release_task  # noqa: E402


TEMPLATES = {
    'config': [
        'Open the configuration associated with the service selected in the context and report its deployment region.',
        'Which region is configured for the currently selected service? Read its matching config.',
        '请读取上下文中当前选中服务对应的配置，并返回部署区域。',
        '当前选中的服务配置在哪个 region？请打开对应文件确认。',
    ],
    'lines': [
        'Read exactly the inclusive line interval {start} through {end} from {path}.',
        'Return only lines {start} to {end}, including both boundaries, from {path}.',
        '请从 {path} 读取第 {start} 到第 {end} 行，包含两端。',
        '只返回 {path} 中从第 {start} 行至第 {end} 行的片段。',
    ],
    'search': [
        'Use a literal filename search to find files under {folder} containing {marker}.',
        'Which paths below {folder} contain the exact text {marker}? Treat the text literally.',
        '请在 {folder} 下按固定字符串 {marker} 搜索并返回匹配文件。',
        '列出 {folder} 中正文含有原样字符串 {marker} 的文件路径。',
    ],
    'git_status': [
        'Report the short working-tree status of this repository, including changed and untracked files.',
        'Which files are currently modified or untracked in this checkout? Use the short Git status.',
        '请用简短 Git 状态列出这个工作区已修改和未跟踪的文件。',
        '查看当前仓库工作树状态，返回变动文件和新文件。',
    ],
    'git_log': [
        'Return only the subject line of the newest commit in this local repository.',
        'What title is recorded on the tip commit? Read the latest local Git subject.',
        '请返回本地仓库最近一次提交的主题行。',
        '查询当前 HEAD 对应的最新提交标题，只要主题。',
    ],
    'health': [
        'Read the status field from the health endpoint selected in the context.',
        'Check the service health address provided by the context and return its status.',
        '请访问上下文提供的健康检查地址并返回 status。',
        '读取已选服务健康端点中的状态字段。',
    ],
    'draft': [
        'Prepare a review-only write proposal for {path} whose complete decoded body is {content}. Do not apply it.',
        'Draft a file write for {path}; preserve every character in the decoded JSON body {content}, without execution.',
        '请为 {path} 生成待审核写入草稿，正文完整取自 JSON {content} 的解码结果，不要执行。',
        '只拟定写入提案：目标 {path}，内容为 JSON 字符串 {content} 解码后的全部文字。',
    ],
    'missing_tool': [
        'Return the complete text of {path}, but use only the tools currently available in context.',
        'Open {path} and show all of its contents with the listed interface.',
        '请用当前可用工具读取 {path} 的完整正文。',
        '查看 {path} 的全部内容，只能使用上下文里列出的工具。',
    ],
    'invalid_range': [
        'Use the requested bounds exactly for {path}: start {start}, end {end}.',
        'The requested line range for {path} is {start} through {end}; do not repair it.',
        '请按原样处理 {path} 的行边界：起点 {start}，终点 {end}。',
        '读取请求给出的范围 {start} 到 {end}，目标是 {path}，不要修改边界。',
    ],
}


def clone_with_prompt(row, kind, language, template, instance):
    source = json.loads(json.dumps(row))
    source['id'] = f'generalization-v6-{kind}-{language}-{template}-{instance}'
    source['family_id'] = f'generalization-v6-{kind}-{language}-wording-{template}'
    source['seed_id'] = source['id']
    source['source'] = 'fresh_authored_generalization_training'
    path = source.get('args', {}).get('path', 'the selected file')
    start = source.get('args', {}).get('start_line', 1)
    end = source.get('args', {}).get('end_line', 2)
    command = source.get('args', {}).get('cmd', '')
    marker = command.split("-- '", 1)[1].split("' '", 1)[0] if "-- '" in command else 'the requested literal'
    folder = command.rsplit("'", 2)[-2] if command.count("'") >= 4 else 'the selected directory'
    content = json.dumps(source.get('args', {}).get('content', ''), ensure_ascii=False)
    source['prompt'] = TEMPLATES[kind][template].format(
        path=path, start=start, end=end, marker=marker, folder=folder, content=content)
    source['language'] = language
    return source


def additions(rows):
    result = []
    # New concrete values are generated by make_release_task, not copied from
    # scored rows. Four semantic wordings per language and 64 instances each
    # gives balanced new families while retaining the V5 data mix.
    for kind, templates in TEMPLATES.items():
        base_template = 0 if kind not in {'invalid_range'} else 0
        for template, wording in enumerate(templates):
            language = 'en' if template < 2 else 'zh'
            for instance in range(64):
                row = make_release_task(kind, base_template if language == 'en' else 2,
                                        template * 64 + instance, 'train', 'generalization-v6')
                result.append(clone_with_prompt(row, kind, language, template, instance))
    return result


def main():
    source = ROOT / 'data/pilots/release-context-correction-v5'
    rows = [json.loads(line) for line in (source / 'train.jsonl').read_text(encoding='utf-8').splitlines()]
    combined = rows + additions(rows)
    random.Random('release-generalization-v6').shuffle(combined)
    seen, unique = {}, []
    for row in combined:
        key = canonical_json(public_record(row))
        label = canonical_json({'tool': row['tool'], 'args': row['args']})
        if key in seen and seen[key] != label:
            raise ValueError(f'Conflicting labels for {row["id"]}')
        if key not in seen:
            seen[key] = label
            unique.append(row)
    output = ROOT / 'data/pilots/release-generalization-v6'
    output.mkdir(parents=True, exist_ok=False)
    (output / 'train.jsonl').write_text(
        ''.join(json.dumps(row, ensure_ascii=False) + '\n' for row in unique), encoding='utf-8')
    for split in ['development', 'evaluation']:
        (output / f'{split}.jsonl').write_bytes((source / f'{split}.jsonl').read_bytes())
    manifest = {
        'version': 'release-generalization-v6',
        'source': 'Fresh authored semantic wording families added after failed V5 held-out results; no scored rows imported.',
        'parent_train_sha256': hashlib.sha256((source / 'train.jsonl').read_bytes()).hexdigest(),
        'generator_sha256': hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
        'dropped_identical_duplicates': len(combined) - len(unique),
        'label_conflicts': 0,
        'evaluation_unchanged': True,
        'splits': {},
    }
    inputs, families = {}, {}
    for split in ['train', 'development', 'evaluation']:
        path = output / f'{split}.jsonl'
        records = [json.loads(line) for line in path.read_text(encoding='utf-8').splitlines()]
        inputs[split] = {canonical_json(public_record(record)) for record in records}
        families[split] = {record['family_id'] for record in records}
        manifest['splits'][split] = {
            'tasks': len(records), 'families': len(families[split]),
            'sha256': hashlib.sha256(path.read_bytes()).hexdigest(),
            'kinds': dict(Counter(record['kind'] for record in records)),
        }
    for left in inputs:
        for right in inputs:
            if left != right and (inputs[left] & inputs[right] or families[left] & families[right]):
                raise ValueError('Cross-split overlap')
    manifest.update(cross_split_families=0, cross_split_exact_inputs=0)
    (output / 'manifest.json').write_text(json.dumps(manifest, indent=2), encoding='utf-8')
    (output / 'generator.py').write_bytes(Path(__file__).read_bytes())
    print(json.dumps(manifest, indent=2))


if __name__ == '__main__':
    main()
